CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
GRAPH_TOKEN_INDEX = -200
USER_GRAPH_TOKEN_INDEX = -201
BUSINESS_GRAPH_TOKEN_INDEX = -202
DEFAULT_GRAPH_TOKEN = "<graph>"
DEFAULT_USER_GRAPH_TOKEN = "<user_graph>"
DEFAULT_BUSINESS_GRAPH_TOKEN = "<business_graph>"
DEFAULT_GRAPH_START_TOKEN = "<GH>"
DEFAULT_GRAPH_END_TOKEN = "</GH>"
DEFAULT_GRAPH_PAD_ID = -500

GRAPH_TOKEN_TO_INDEX = {
    DEFAULT_GRAPH_TOKEN: GRAPH_TOKEN_INDEX,
    DEFAULT_USER_GRAPH_TOKEN: USER_GRAPH_TOKEN_INDEX,
    DEFAULT_BUSINESS_GRAPH_TOKEN: BUSINESS_GRAPH_TOKEN_INDEX,
}
GRAPH_TOKEN_INDICES = tuple(GRAPH_TOKEN_TO_INDEX.values())
